echo Running mosquitto commands...
echo Creating password file with testuser...
mosquitto_passwd -c config/passwd testuser
@REM Use "password" as the password when prompted.
echo Password file created.
echo Starting mosquitto broker with configuration...
mosquitto -v -c config/mosquitto.conf
pause